// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *bannerPrincipal → qualidadesPizzaPizza*
 */
export interface BannerprincipalDocumentDataQualidadespizzapizzaItem {
  /**
   * imagemQualidades field in *bannerPrincipal → qualidadesPizzaPizza*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bannerprincipal.qualidadespizzapizza[].imagemqualidades
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagemqualidades: prismic.ImageField<never>;

  /**
   * tituloQualidade field in *bannerPrincipal → qualidadesPizzaPizza*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bannerprincipal.qualidadespizzapizza[].tituloqualidade
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tituloqualidade: prismic.KeyTextField;

  /**
   * descricaoQualidade field in *bannerPrincipal → qualidadesPizzaPizza*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bannerprincipal.qualidadespizzapizza[].descricaoqualidade
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricaoqualidade: prismic.KeyTextField;
}

/**
 * Item in *bannerPrincipal → avaliaçõesClientes*
 */
export interface BannerprincipalDocumentDataAvaliacoesclientesItem {
  /**
   * aspas field in *bannerPrincipal → avaliaçõesClientes*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bannerprincipal.avaliacoesclientes[].aspas
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  aspas: prismic.ImageField<never>;

  /**
   * avaliaçõesClientes field in *bannerPrincipal → avaliaçõesClientes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bannerprincipal.avaliacoesclientes[].avaliacoesclientes
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  avaliacoesclientes: prismic.KeyTextField;

  /**
   * nomeCliente field in *bannerPrincipal → avaliaçõesClientes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bannerprincipal.avaliacoesclientes[].nomecliente
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nomecliente: prismic.KeyTextField;
}

/**
 * Content for bannerPrincipal documents
 */
interface BannerprincipalDocumentData {
  /**
   * tituloPrincipal field in *bannerPrincipal*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: bannerprincipal.tituloprincipal
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tituloprincipal: prismic.TitleField;

  /**
   * descricaoPrincipal field in *bannerPrincipal*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bannerprincipal.descricaoprincipal
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricaoprincipal: prismic.RichTextField;

  /**
   * textoBotao field in *bannerPrincipal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bannerprincipal.textobotao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  textobotao: prismic.KeyTextField;

  /**
   * imagemPrincipal field in *bannerPrincipal*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bannerprincipal.imagemprincipal
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagemprincipal: prismic.ImageField<never>;

  /**
   * qualidadesPizzaPizza field in *bannerPrincipal*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bannerprincipal.qualidadespizzapizza[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  qualidadespizzapizza: prismic.GroupField<
    Simplify<BannerprincipalDocumentDataQualidadespizzapizzaItem>
  >;

  /**
   * avaliaçõesClientes field in *bannerPrincipal*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bannerprincipal.avaliacoesclientes[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  avaliacoesclientes: prismic.GroupField<
    Simplify<BannerprincipalDocumentDataAvaliacoesclientesItem>
  >;

  /**
   * horarioSemana field in *bannerPrincipal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bannerprincipal.horariosemana
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  horariosemana: prismic.KeyTextField;

  /**
   * horarioFinalsemana field in *bannerPrincipal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bannerprincipal.horariofinalsemana
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  horariofinalsemana: prismic.KeyTextField;

  /**
   * endereçoLoja field in *bannerPrincipal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bannerprincipal.enderecoloja
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  enderecoloja: prismic.KeyTextField;

  /**
   * numeroWhatsapp field in *bannerPrincipal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bannerprincipal.numerowhatsapp
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  numerowhatsapp: prismic.KeyTextField;
}

/**
 * bannerPrincipal document from Prismic
 *
 * - **API ID**: `bannerprincipal`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BannerprincipalDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BannerprincipalDocumentData>,
    "bannerprincipal",
    Lang
  >;

export type AllDocumentTypes = BannerprincipalDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BannerprincipalDocument,
      BannerprincipalDocumentData,
      BannerprincipalDocumentDataQualidadespizzapizzaItem,
      BannerprincipalDocumentDataAvaliacoesclientesItem,
      AllDocumentTypes,
    };
  }
}
